# Generated by Django 3.0.6 on 2020-10-24 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_type', models.CharField(max_length=50)),
                ('bus_number', models.CharField(max_length=40)),
                ('bus_places', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('message', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('bamenda', 'Bamenda'), ('douala', 'Douala'), ('yaounde', 'Yaounde'), ('buea', 'Buea'), ('bafoussam', 'Bafoussam'), ('ngaoundere', 'Ngaoundere')], max_length=20)),
                ('destination', models.CharField(choices=[('bamenda', 'Bamenda'), ('douala', 'Douala'), ('yaounde', 'Yaounde'), ('buea', 'Buea'), ('bafoussam', 'Bafoussam'), ('ngaoundere', 'Ngaoundere')], max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
