# Generated by Django 3.0.6 on 2020-10-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20201024_0748'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
