# Generated by Django 3.0.6 on 2020-10-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
